/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcCalc.h"


void
prog_100(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	operandos  add_100_arg;
	int  *result_2;
	operandos  sub_100_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_100(&add_100_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = sub_100(&sub_100_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int add(CLIENT *clnt, int x, int y) {
operandos ops;
int *result;
/* Preenche struct operandos p ser enviada ao outro lado */
ops.x = x;
ops.y = y;
/* Chama o stub cliente criado pelo rpcgen */
result = add_100(&ops,clnt);
if (result==NULL) {
fprintf(stderr,"Problema na chamada RPC\n");
exit(0);
}
return(*result);
} /* fim função add local */
int sub(CLIENT *clnt, int x, int y) {
operandos ops;
int *result;
/* Preenche struct operandos p ser enviada ao outro lado */
ops.x = x;
ops.y = y;
/* Chama o stub cliente criado pelo rpcgen */
result = sub_100(&ops,clnt);
if (result==NULL) {
fprintf(stderr,"Problema na chamada RPC\n");
exit(0);
}
return(*result);
} /* fim funcao sub local*/


int
main (int argc, char *argv[])
{
	CLIENT *clnt;
int x,y;
if (argc!=4) {
fprintf(stderr,"Uso: %s hostname num1 num2\n",argv[0]);
exit(0);
}
clnt = clnt_create(argv[1], PROG, VERSAO, "udp");
/* Garantindo a criacao da ligacao com o remoto */
if (clnt == (CLIENT *) NULL) {
clnt_pcreateerror(argv[1]);
exit(1);
}
/* Recupera os 2 operandos passados como argumento */
x = atoi(argv[2]);
y = atoi(argv[3]);
printf("%d + %d = %d\n",x,y, add(clnt,x,y));
printf("%d - %d = %d\n",x,y, sub(clnt,x,y));
return(0);
}
